gText_Birch_Welcome::
	.string "Good morning, kiddo!\p"
	.string "...\p"
	.string "Hello sleepy, I'm DAD!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "FARFETCH'D and I are going\n"
	.string "for a jog.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "One of you still in bed, while\n"
	.string "the other one's gone already!\p"
	.string "You really take after your mom.\p"
	.string "Can you go check on your sibling?\n"
	.string "I heard all the kids around town\l"
	.string "are planning a big event\l"
	.string "for your birthday tomorrow.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now go and get ready!$"

gText_Birch_BoyOrGirl::
	.string "Don't leave the others\n"
	.string "waiting.$"

gText_Birch_WhatsYourName::
	.string "I heard others calling\n"
	.string "your name outside.$"

gText_Birch_SoItsPlayer::
	.string "They said {PLAYER}{KUN},\n"
	.string "right?$"

gText_Birch_YourePlayer::
	.string "Anyway...\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Have a nice day exploring DEWFORD,\n"
	.string "{PLAYER}{KUN}!\p"
	.string "$"
